<Project>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <NoWarn>ASP0014</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Finbuckle.MultiTenant.AspNetCore" Version="10.0.2" />
    <PackageReference Include="jcamp.MongoFramework.AspNetCore.Identity" Version="3.0.0" />
  </ItemGroup>

</Project>