<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PackageId>jcamp.Finbuckle.MultiTenant.MongoFramework</PackageId>
    <Version>3.0.0</Version>
    <AssemblyName>Finbuckle.MultiTenant.MongoFramework</AssemblyName>
    <Title>Finbuckle.MultiTenant.MongoFramework</Title>
    <Description>Finbuckle.MultiTenant integration with MongoFramework providing tenant store and data isolation</Description>
    <Authors>John Campion Jr</Authors>
    <Copyright>Copyright © John Campion Jr</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="jcamp.MongoFramework" Version="3.0.0" />
    <PackageReference Include="Finbuckle.MultiTenant" Version="10.0.2" />
  </ItemGroup>

</Project>
